###########
# site.title
url:      'https://thebuildingcompany.co'
title:    'The Building Company'
subtitle: 'Expert builders in Milton Keynes & surrounding areas.'
description: 'Expert builders in Milton Keynes & surrounding areas. Our services include New Builds, Extensions, and Refurbishments & Alterations.'

permalink: pretty

#########################
# more settings

markdown: kramdown

sass:
  style: compressed

exclude:
- README.md
- LICENSE.md

plugins:
  - jekyll-sitemap